#version: '3.9'

services:
  web:
    build: .
    expose:
      - "8000"
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Mapowanie portów kontenera na hosta, dla data azure studio

  nginx:
    image: nginx:latest
    ports:
      - "80:80"    # Przekierowanie HTTP
      - "443:443"  # Przekierowanie HTTPS
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Konfiguracja NGINX
      - ./nginx/certs:/etc/ssl/certs                      # Certyfikaty SSL
      - ./nginx/private:/etc/ssl/private                  # Klucz prywatny SSL

volumes:
  postgres_data:
