version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
