# Generated by Django 4.2 on 2025-01-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_message_signature_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rsa_private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rsa_public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
