# Generated by Django 4.2 on 2025-01-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_message_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
